import Head from "next/head";
import StreamPreview from "../components/StreamPreview";
import { useState, useSyncExternalStore } from "react";

const liveStreams = [
  {
    channelName: "theprimeagen",
    title: "Programming a twitch downloader in GO",
    game: "Programming",
  },
];

async function fetchData() {
  const response = await fetch("/api/twitch");
  if (response.ok) {
    const data = await response.json();
    // Process the data as needed
  } else {
    console.error("Failed to fetch data");
  }
}

export default function Home() {
  //fetchData();
  const [counter, setCounter] = useState(0);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <StreamPreview liveStream={liveStreams[0]}></StreamPreview>
        <button
          onClick={() => {
            setCounter(counter + 1);
          }}
        >
          CLick me
        </button>
      </main>
    </>
  );
}
