import Head from "next/head";
import Link from "next/link";
import Header from "../components/Header";
import SearchBar from "../components/SearchBar";
import LeftSideBar from "../components/LeftSideBar";
import { SearchProvider } from "../contexts/SearchContext";
import "./globals.css";

export default function RootLayout({ children }) {
  return (
    <html className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body className="">
        <SearchProvider>
          <main className="bg-gray-800 text-gray-200 min-h-[100vh]">
            <Header />
            <div className="flex">
              <LeftSideBar />
              <div className="main-content-div">{children}</div>
            </div>
          </main>
        </SearchProvider>
      </body>
    </html>
  );
}
