import Head from "next/head";
import Link from "next/link";
import SearchBar from "../components/SearchBar";
import { SearchProvider } from "../contexts/SearchContext";
import "./globals.css";

export default function RootLayout({ children }) {
  return (
    <html className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body className="">
        <main className="bg-gray-600 text-gray-300 min-h-[100vh]">
          <SearchProvider>
            <SearchBar />
            <Link href="/live">Live</Link>
            <Link href="/">Home</Link>
            <Link href="/channel">Channel</Link>
            <h1 className="text-3xl font-bold underline">Hello world!</h1>
            {children}
          </SearchProvider>
        </main>
      </body>
    </html>
  );
}
